### ISSUE TITLE
WindowsError: [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by btbroot** [vfuse/nixstatsagent#1]
On Windows the execution thread throws:

```
Exception in thread execution:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\IEUser\nixstatsagent\nixstatsagent.py", line 114, in _execution
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

**Comment by vfuse** [comment]
Import sys and change the first argement of popen from (task,) to [sys.executable, task]

**Comment by btbroot** [comment]
Yes, I did that. Assuming, that plugins will be written in Python only, that would work.
