### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SIGKILL'

### ISSUE THREAD

**Issue by btbroot** [vfuse/nixstatsagent#2]
On Windows the execution thread throws:
```
Exception in thread execution:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\IEUser\nixstatsagent\nixstatsagent.py", line 128, in _execution
    os.kill(process.pid, signal.SIGKILL)
AttributeError: 'module' object has no attribute 'SIGKILL'
```

**Comment by btbroot** [comment]
I believe, I fixed that without any additional magic, just by using SIGTERM instead of SIGKILL. It will be now a subject of testing how SIGTERM would be handled by the most stubborn plugins. In any case though, I believe, it's up to the administrator, to use a brutal SIGKILL if he really wants so, since all good dogies should obey SIGTERM!
