### ISSUE TITLE
ValueError: insecure string pickle on Windows 10

### ISSUE THREAD

**Issue by vfuse** [vfuse/nixstatsagent#5]
> Exception in thread execution:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "nixstatsagent.py", line 132, in _execution
    payload = pickle.loads(stdout) if stdout else None
  File "C:\Python27\lib\pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 972, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle

Pickle data: 

> (dp0
I0
(dp1
S'interrupt'
p2
F0.0
sS'idle'
p3
F80.0
sS'dpc'
p4
F0.0
sS'user'
p5
F12.3
sS'system'
p6
F7.7
ss.

**Comment by vfuse** [comment]
Windows outputs newlines in the pickle as \r\n replacing this with just \n seems to solve this issue for now.
